export const roles = [
  "Associate Developer",
  "Director",
  "Senior Technical Manager",
  "Timesheet Manager",
  "SVP",
  "Manager",
  "Director - Delivery",
  "Senior Director",
  "Executive Vice President – Business Execution & Transformation",
  "Associate Director - Account Management",
  "Sr. Vice President - Tax & Tech",
  "Full Stack Engineer",
  "Solution Analyst",
];
